language: ruby

rvm:
  - 2.7.0

# before_install:
#   - sudo apt-get -y install ruby-full build-essential zlib1g-dev
# before_script:
#  - chmod +x ./script/cibuild

script:
  - gem install bundler:2.1.4
  - bundle update --bundler
# - if [[ "$TRAVIS_COMMIT_MESSAGE" =~ "New-Post" ]]; then export PUSH_NOTIFICATION="yes";
#   else export PUSH_NOTIFICATION="no"; fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: true
  verbose: true
  on:
    branch: master

# after_success:
#   - chmod +x ./scripts/new_post_push_message.sh
#   - "./scripts/new_post_push_message.sh $OPEN_SIGNAL_API $PUSH_NOTIFICATION"

env:
  global:
    - secure: lZsZ1esQxqd5HNfm7bu4CWB6bkak5vmM8mpC7QbnCiZfDtCd9ybuKq1DPqB9f7E3EJ53Opp95BlQ6sL8z1C3VKUh44FT8QbwWK1Yxy5mUn3LIBtnnoXeKFeht34aHCNt93Ui+PaDw3R6yP9jzOGNN4x+L0LAgJyqUwspuJ/GMe5cdS/YO0/a7vkZSlHAuj4+f2IEHjdeTbspWuMJAd9rtpERkFJf7bJ6ud3latatMV8SJ2F1X+X5pnCtgE5LD+fKDCqZ7dHx0SYorL75q6pPxRnq04cmiB9qGOZ2gd8PNIuvgDXpgpoDZ6tJqTMTP+IXzsVEwDXHr6+jmEzbHyw1CYRJ3zIYujxnouQD0IZ/qnM6Fcoudxh9egqCqg4fGkWqyhS0OSlLclRYH+UQjvzd4oVRzHJnbWpabQyzAlsYJvm60KDod2Sk6XBuyg8LoAmAyR/IBsnkBu9YiFKQe2w3O+IQgKmIx+OKxknQguzoeE+0VCmWIxp2CISF9rY7p3Q6FJSBUUFBylqGqvbU36TNHjlGZzwCSdguANxR+BnRCnEkJvmDJd+10YXjsCiyi2i1aR06wdNAeSaZ6Lvn1G6U+nWSsa2Zi+LQcHQFvoE200cQEsyB6B/bIgYkf205PZRHPPn7uaflQguG5GpmtnrpnscJOJZGSciW7JyyueuCn9k=
  
